---
title: Einkaufsmanager
---

sequenceDiagram
    participant Einkaufmanager
    participant Lieferant
    participant Bestellung
    participant Bauteilkatalog


    Einkaufmanager->>+Lieferant: frag bestellungsnummer an
    Lieferant->>+Bestellung: holt bestellungsnummer
    Lieferant->>+Einkaufmanagereferant: liefert Bestellungsnummer
    
    loop für jeden artikel
        Einkaufmanager->>+Bauteilkatalog: preis abfrage
        Einkaufmanager->>+Einkaufmanager: preis zusammenrechnen
    end
    

