---
title: TITEL
---

stateDiagram-v2

%% https://mermaid.js.org/syntax/stateDiagram.html#state-diagrams
   
    [*] --> No_Sensor_triggerd
    No_Sensor_triggerd --> Sensor_triggerd
    Sensor_triggerd --> höhere_Sensitivität: nach 45 sek
    höhere_Sensitivität --> No_Sensor_triggerd: nach 5min

    state höhere_Sensitivität{

        [*] --> Sensor_in_5min_triggerd

    }

Sensor_in_5min_triggerd --> Alarm
    
note right of Alarm : This is the note to the right.